spring:
  application:
    name: fraud-insight-service
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud_service
    username: fraud_user
    password: fraud_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: "fraud-insight-group"
      properties:
        spring.json.trusted.packages: "pl.kul.fraud-insight_service.model.kafka"
        spring.json.value.default.type: "pl.kul.fraud_insight_service.model.kafka.QueueJoinedEvent"
        spring.json.use.type.headers: false
server:
  port: 8082
